Dependencies:
- 'on': ['Linux/Qt6', 'Linux/Qt6Next', 'FreeBSD/Qt6', 'Windows/Qt6']
  'require':
    'frameworks/extra-cmake-modules': 'Frameworks/6.24'
    'frameworks/karchive': 'Frameworks/6.24'
    'frameworks/kconfig': 'Frameworks/6.24'
    'frameworks/kcoreaddons': 'Frameworks/6.24'
    'frameworks/kparts': 'Frameworks/6.24'
    'frameworks/ki18n': 'Frameworks/6.24'
    'frameworks/kio': 'Frameworks/6.24'
    'graphics/kdiagram': '@latest-kf6'
- 'on': ['Linux/Qt6', 'Linux/Qt6Next', 'FreeBSD/Qt6']
  'require':
    'graphics/kgraphviewer': '@same'

Options:
  require-passing-tests-on: [ 'Linux', 'FreeBSD' ]
