Dependencies:
- 'on': ['Linux/Qt6', 'FreeBSD/Qt6', 'Windows/Qt6']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/karchive': '@latest-kf6'
    'frameworks/kconfig': '@latest-kf6'
    'frameworks/kcoreaddons': '@latest-kf6'
    'frameworks/kparts': '@latest-kf6'
    'frameworks/ki18n': '@latest-kf6'
    'frameworks/kio': '@latest-kf6'
    'graphics/kdiagram': '@latest-kf6'
- 'on': ['Linux/Qt6', 'FreeBSD/Qt6']
  'require':
    'graphics/kgraphviewer': '@latest-kf6'
- 'on': ['Linux/Qt5', 'FreeBSD/Qt5', 'Windows/Qt5']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/karchive': '@stable'
    'frameworks/kconfig': '@stable'
    'frameworks/kcoreaddons': '@stable'
    'frameworks/kparts': '@stable'
    'frameworks/kio': '@stable'
    'frameworks/ki18n': '@stable'
    'graphics/kdiagram': '@latest'
- 'on': ['Linux/Qt5', 'FreeBSD/Qt5', 'macOS/Qt5']
  'require':
    'graphics/kgraphviewer': '@latest'